fdpm_list_conversations:
    path: /conversation
    defaults: { _controller: FDPrivateMessageBundle:Conversation:list }

fdpm_new_conversation:
    path:     /conversation/new
    defaults: { _controller: FDPrivateMessageBundle:Conversation:create }

fdpm_show_conversation:
    path: /conversation/{conversation}
    defaults: { _controller: FDPrivateMessageBundle:Conversation:show }
    requirements:
        conversation: \d+