services:
    fdpm.listener.leave_conversation:
        class: FD\PrivateMessageBundle\EventSubscriber\LeaveConversationSubscriber
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_subscriber }

    fdpm.conversation_voter:
        class: FD\PrivateMessageBundle\Security\ConversationVoter
        public: false
        tags:
            - { name: security.voter }
