services:
    fdpm.listener.leave_conversation:
        class: FD\PrivateMessageBundle\EventSubscriber\LeaveConversationSubscriber
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_subscriber }
