language: php
 
php:
    - 5.6

 
matrix:
    allow_failures:
        - php: hhvm
 
before_script:
    - composer self-update
    - composer install
    - vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
 
script:
    - vendor/bin/phpcs --standard=Symfony2 --extensions=php --ignore=vendor -n  .
 
notifications:
    email: false