<?php

namespace FD\PrivateMessageBundle\Repository;

/**
 * PrivateMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
