<?php

namespace FireDIY\PrivateMessageBundle\Repository;

/**
 * RecipientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipientRepository extends \Doctrine\ORM\EntityRepository
{
}
